# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lbl_ip = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ip.setObjectName("lbl_ip")
        self.gridLayout.addWidget(self.lbl_ip, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lbl_mac = QtWidgets.QLabel(self.centralwidget)
        self.lbl_mac.setObjectName("lbl_mac")
        self.gridLayout.addWidget(self.lbl_mac, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.lbl_gw = QtWidgets.QLabel(self.centralwidget)
        self.lbl_gw.setObjectName("lbl_gw")
        self.gridLayout.addWidget(self.lbl_gw, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.lbl_iface = QtWidgets.QLabel(self.centralwidget)
        self.lbl_iface.setObjectName("lbl_iface")
        self.gridLayout.addWidget(self.lbl_iface, 1, 3, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tbl_hosts = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_hosts.setObjectName("tbl_hosts")
        self.tbl_hosts.setColumnCount(0)
        self.tbl_hosts.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_hosts)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menu_Operations = QtWidgets.QMenu(self.menubar)
        self.menu_Operations.setObjectName("menu_Operations")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuToolbar = QtWidgets.QMenu(self.menuSettings)
        self.menuToolbar.setObjectName("menuToolbar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.act_scan = QtWidgets.QAction(MainWindow)
        self.act_scan.setObjectName("act_scan")
        self.act_cut = QtWidgets.QAction(MainWindow)
        self.act_cut.setObjectName("act_cut")
        self.action_Help = QtWidgets.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionShow_Icons = QtWidgets.QAction(MainWindow)
        self.actionShow_Icons.setCheckable(True)
        self.actionShow_Icons.setObjectName("actionShow_Icons")
        self.actionShow_Icons_Text = QtWidgets.QAction(MainWindow)
        self.actionShow_Icons_Text.setCheckable(True)
        self.actionShow_Icons_Text.setObjectName("actionShow_Icons_Text")
        self.menu_Operations.addAction(self.act_scan)
        self.menu_Operations.addAction(self.act_cut)
        self.menu_Help.addAction(self.action_Help)
        self.menu_Help.addAction(self.action_About)
        self.menuToolbar.addAction(self.actionShow_Icons)
        self.menuToolbar.addAction(self.actionShow_Icons_Text)
        self.menuSettings.addAction(self.menuToolbar.menuAction())
        self.menubar.addAction(self.menu_Operations.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.act_scan)
        self.toolBar.addAction(self.act_cut)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NetShut"))
        self.label.setText(_translate("MainWindow", "IP Address :"))
        self.lbl_ip.setText(_translate("MainWindow", "<b>192.168.1.14</b>"))
        self.label_3.setText(_translate("MainWindow", "MAC Address :"))
        self.lbl_mac.setText(_translate("MainWindow", "<b>5c:f9:6a:23:7c:1a</b>"))
        self.label_5.setText(_translate("MainWindow", "Gateway IP :"))
        self.lbl_gw.setText(_translate("MainWindow", "<b>192.168.1.1</b>"))
        self.label_2.setText(_translate("MainWindow", "Interface :"))
        self.lbl_iface.setText(_translate("MainWindow", "<b>wlp2s0</b>"))
        self.menu_Operations.setTitle(_translate("MainWindow", "Operatio&ns"))
        self.menu_Help.setTitle(_translate("MainWindow", "?"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settin&gs"))
        self.menuToolbar.setTitle(_translate("MainWindow", "Toolbar"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Main Toolbar"))
        self.act_scan.setText(_translate("MainWindow", "&Scan"))
        self.act_cut.setText(_translate("MainWindow", "&Cut All"))
        self.action_Help.setText(_translate("MainWindow", "&Help"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.actionShow_Icons.setText(_translate("MainWindow", "Show Icons"))
        self.actionShow_Icons_Text.setText(_translate("MainWindow", "Show Icons && Text"))

